title: Chelsea DSouza's Portfolio # your name (or website title) here
logo: "/images/profile-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Data Analyst Professional</strong> <br>
  <br><br>
  <strong>About me:</strong> <br>
      My work focuses on <strong>data visualization, analytics automation,</strong> and transforming raw data into clear, actionable stories.<br>
  <br><br>
  üåç <strong>Location:</strong> Berlin, Germany <br>
  <a href="https://www.linkedin.com/in/chelsea-a-d-souza-2701/" target="_blank" style="display:inline-flex;align-items:center;gap:6px;">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg" width="15" height="15" alt="LinkedIn" style="filter:invert(23%) sepia(94%) saturate(1500%) hue-rotate(190deg) brightness(105%) contrast(90%);">
  Connect on LinkedIn</a>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
