title: Chelsea DSouza's Project Portfolio # your name (or website title) here
logo: "/images/profile-modified.png?raw=true" # your photo (or logo) here
description: > 
# your text below (remove <br> elements if you don't need line breaks)
   
  
  <a href="https://www.linkedin.com/in/chelsea-a-d-souza-2701/" target= "_blank">View My LinkedIn Profile</a> <!-- the  target= "_blank" is what made the link open in another tab. -->
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
