title: Chelsea DSouza # your name (or website title) here
logo: "/images/profile-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Digital Business & Data Science Graduate</strong>
  <br><br>
  <strong>About me:</strong> <br>
    Data Analyst with a focus on reporting, data visualization, and business insights. Committed to data-driven decision-making.
  <br><br>
  üåç <strong>Location:</strong> Berlin, Germany
  <br><br>
  <a href="https://www.linkedin.com/in/chelsea-a-d-souza-2701/" target="_blank" style="display:inline-flex;align-items:center;gap:6px;">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg" width="15" height="15" alt="LinkedIn" style="filter:invert(18%) sepia(92%) saturate(2825%) hue-rotate(197deg) brightness(93%) contrast(92%);">
  View My LinkedIn Profile</a>
  <br><br>
  ‚öôÔ∏è <strong>Skills:</strong>
   <br><br>
  <a href="https://www.linkedin.com/in/chelsea-a-d-souza-2701/" target= "_blank">View My LinkedIn Profile</a> <!-- the  target= "_blank" is what made the link open in another tab. -->
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
